config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :experiences

  resources :profiles

  resources :tech_skills

  resources :certificationals

  resources :educations

  resources :addresses

  resources :employees

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  
  root to: "resumes#index"
   
      get 'index' => "resumes#index"
      get 'about_us' => "resumes#about_us"
      get 'contact_us' => "resumes#contact_us"
      get 'resume_edit' => "resumes#resume_edit"
      get '/export_to_pdf' => "resumes#export_to_pdf"
      get '/resume' => "resumes#resume"
      get '/resume1' => "resumes#resume1"
      get '/resume2' => "resumes#resume2"
      get '/demo_resume' => "resumes#demo_resume"
 
 
    
    
    get "/404", :to => 'errors#file_not_found', via: :all
    get "/422", :to => 'errors#unprocessable', via: :all
    get "/500", :to => 'errors#internal_server_error', via: :all

   

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  middle_name   :string(255)
#  last_name     :string(255)
#  email         :string(255)
#  age           :integer
#  date_of_birth :date
#  created_at    :datetime
#  updated_at    :datetime
#  user_id       :integer
#



class Employee < ActiveRecord::Base
	has_many :addresses
	has_many :educations
	has_many :tech_skills
	has_many :certificational
	belongs_to :users
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employee = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show

  end

  # GET /employees/new
  def new
    @employee = current_user.employee || Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    params[:employee][:user_id] = current_user.id
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to "/educations/new", notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :middle_name, :last_name, :email, :age, :date_of_birth, :user_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="container">
 <div class="jumbotron">
    

        
<%= form_for @employee ,:html=>{:class=>"form-horizontal" ,:role=>"form"} do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   
  <div class="form-group">
<h2 style="color:OrangeRed"><center>Personal Information</center> </h2><hr>
    <label for="inputEmail3" class="col-sm-2 control-label">First Name</label>
    <div class="col-sm-6">

      <%= f.text_field :first_name ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"first name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Middle  Name</label>
    <div class="col-sm-6">
      <%= f.text_field :middle_name ,:class =>"form-control", :style =>"border:1px groove #F7730E;" , :placeholder=>"Middle  Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Last Name</label>
    <div class="col-sm-6">
      <%= f.text_field :last_name ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"Last  Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-6">
      <%= f.text_field :email ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"Email" %>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Age</label>
    <div class="col-sm-6">
      <%= f.text_field :age ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"Age"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">DOB</label>
    <div class="col-sm-6">
      <%= f.text_field :date_of_birth ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"date of birth"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      
      <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
      <%= f.submit 'Enter Education Details', :class => 'btn btn-primary'  %>

    </div>
    <div id="image">
  <img src="../assets/newemp.png" alt="Logo"  width="450px" height="400px"align="left" style="
left: 39px;
top: -418px">
</div>
  </div>
    <% end %>




  </div>
  </div>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="container">
 <div class="jumbotron">
                 <h2 style="color:OrangeRed"><center>Listing employees </center></h2>       
               <hr>
              
              <div class="panel panel-default">
                <div class="panel-body">
                  <table class="table table-striped footable">
                    
                    <thead>

                      <tr>
                          <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Date of birth</th>
      <th colspan="3"> Action</th>
                      </tr>
                    </thead>
                    <tbody>
                       <% @employee.each do |employee| %>
                      <tr>
                       
        <td><%= employee.first_name %></td>
        <td><%= employee.middle_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
                      
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>


<%#= link_to 'New Employee', new_employee_path %>
</div>

app/views/employees/new.html.erb
<h4><center></center></h4>

<%= render 'form' %>

app/views/employees/show.html.erb
<div class="container">
 <div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @employee.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employee.date_of_birth %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

</div>
</div>