config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :experiences

  resources :profiles

  resources :tech_skills

  resources :certificationals

  resources :educations

  resources :addresses

  resources :employees

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  
  root to: "resumes#index"
   
      get 'index' => "resumes#index"
      get 'about_us' => "resumes#about_us"
      get 'contact_us' => "resumes#contact_us"
      get 'resume_edit' => "resumes#resume_edit"
      get '/export_to_pdf' => "resumes#export_to_pdf"
      get '/resume' => "resumes#resume"
      get '/resume1' => "resumes#resume1"
      get '/resume2' => "resumes#resume2"
      get '/demo_resume' => "resumes#demo_resume"
 
 
    
    
    get "/404", :to => 'errors#file_not_found', via: :all
    get "/422", :to => 'errors#unprocessable', via: :all
    get "/500", :to => 'errors#internal_server_error', via: :all

   

end

app/models/experience.rb
# == Schema Information
#
# Table name: experiences
#
#  id             :integer          not null, primary key
#  companyname    :string(255)
#  designation    :string(255)
#  companyprofile :string(255)
#  duration       :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#

class Experience < ActiveRecord::Base
	belongs_to :employee
	belongs_to :users
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  def index
    @experiences = Experience.all
    respond_with(@experiences)
  end

  def show
    respond_with(@experience)
  end

  def new
    @experience =  Experience.new
    respond_with(@experience)
  end

  def edit
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.save
    respond_with(@experience)
  end

  def update
    @experience.update(experience_params)
    respond_with(@experience)
  end

  def destroy
    @experience.destroy
    respond_with(@experience)
  end

  private
    def set_experience
      @experience = Experience.find(params[:id])
    end

    def experience_params
      params.require(:experience).permit(:companyname, :designation, :companyprofile, :duration, :user_id)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<body>
<div class="container">
 <div class="jumbotron">
 

<%= form_for @experience, :html=>{:class=>"form-horizontal" ,:role=>"form"} do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2 style="color:OrangeRed"><center>Experience Details</center></h2><hr>
  <div class="form-group">
    
 
    <label for="inputEmail3" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-6">
      <%= f.text_field :companyname ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"company Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Designation Name</label>
    <div class="col-sm-6">
      <%= f.text_field :designation ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"designation Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Company Profile </label>
    <div class="col-sm-6">
      <%= f.text_field :companyprofile ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"company profile "%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">duration</label>
    <div class="col-sm-6">
      <%= f.text_field :duration ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"duration"%>
    </div>
  </div>
 
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      
      <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
      <%= f.submit 'Enter Experience Details', :class => 'btn btn-primary'  %>
    </div>
       <div id="image">
  <img src="../assets/ed.png" alt="Logo"  align="left" style=" left: 10px;
top: -290px;">
</div>
  </div>
    <% end %>


  </div>
  </div>
</body>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
  
  <div class="container">
 <div class="jumbotron">

             <%= link_to 'Add experience', new_experience_path, :class =>"btn btn-primary pull-right" %>
     <h2 style="color:OrangeRed"><center>Listing experiences </center></h2>       
               <hr>
              <div class="panel panel-default">
                <div class="panel-body">
                  <table class="table table-striped footable">
                    <thead>
    <tr>
      <th>Company Name</th>
      <th>Designation</th>
      <th>Company Profile</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.reverse.each do |experience| %>
      <tr>
        <td><%= experience.companyname %></td>
        <td><%= experience.designation %></td>
        <td><%= experience.companyprofile %></td>
        <td><%= experience.duration %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
 
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

</div>


<br>

<%#= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
  
  <div class="container">
 <div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>Companyname:</strong>
  <%= @experience.companyname %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @experience.designation %>
</p>

<p>
  <strong>Companyprofile:</strong>
  <%= @experience.companyprofile %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @experience.duration %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>
</div>
</div>