config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :experiences

  resources :profiles

  resources :tech_skills

  resources :certificationals

  resources :educations

  resources :addresses

  resources :employees

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  
  root to: "resumes#index"
   
      get 'index' => "resumes#index"
      get 'about_us' => "resumes#about_us"
      get 'contact_us' => "resumes#contact_us"
      get 'resume_edit' => "resumes#resume_edit"
      get '/export_to_pdf' => "resumes#export_to_pdf"
      get '/resume' => "resumes#resume"
      get '/resume1' => "resumes#resume1"
      get '/resume2' => "resumes#resume2"
      get '/demo_resume' => "resumes#demo_resume"
 
 
    
    
    get "/404", :to => 'errors#file_not_found', via: :all
    get "/422", :to => 'errors#unprocessable', via: :all
    get "/500", :to => 'errors#internal_server_error', via: :all

   

end

app/models/certificational.rb
# == Schema Information
#
# Table name: certificationals
#
#  id                 :integer          not null, primary key
#  certification_name :string(255)
#  presentage         :integer
#  institute_name     :string(255)
#  start_date         :date
#  end_date           :date
#  user_id            :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Certificational < ActiveRecord::Base
	belongs_to :employee
	belongs_to :users
end

app/controllers/certificationals_controller.rb
class CertificationalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_certificational, only: [:show, :edit, :update, :destroy]

  # GET /certificationals
  # GET /certificationals.json
  def index
    @certificationals = current_user.certificationals
  end

  # GET /certificationals/1
  # GET /certificationals/1.json
  def show
  end

  # GET /certificationals/new
  def new
    @certificational = Certificational.new
  end

  # GET /certificationals/1/edit
  def edit
  end

  # POST /certificationals
  # POST /certificationals.json
  def create
    @certificational = Certificational.new(certificational_params)
    @certificational.user_id = current_user.id    

    respond_to do |format|
      if @certificational.save
        format.html { redirect_to @certificational, notice: 'Certificational was successfully created.' }
        format.json { render :show, status: :created, location: @certificational }
      else
        format.html { render :new }
        format.json { render json: @certificational.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificationals/1
  # PATCH/PUT /certificationals/1.json
  def update
    respond_to do |format|
      if @certificational.update(certificational_params)
        format.html { redirect_to @certificational, notice: 'Certificational was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificational }
      else
        format.html { render :edit }
        format.json { render json: @certificational.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificationals/1
  # DELETE /certificationals/1.json
  def destroy
    @certificational.destroy
    respond_to do |format|
      format.html { redirect_to certificationals_url, notice: 'Certificational was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificational
      @certificational = Certificational.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificational_params
      params.require(:certificational).permit(:certification_name, :presentage, :institute_name, :start_date, :end_date, :user_id)
    end
end

app/helpers/certificationals_helper.rb
module CertificationalsHelper
end

app/views/certificationals/_form.html.erb
<div class="container">
 <div class="jumbotron">

<%= form_for (@certificational) ,:html=>{:class=>"form-horizontal" ,:role=>"form"}  do |f| %>
  <% if @certificational.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificational.errors.count, "error") %> prohibited this certificational from being saved:</h2>

      <ul>
      <% @certificational.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- 
  <div class="field">
    <%= f.label :certification_name %><br>
    <%= f.text_field :certification_name %>
  </div>
  <div class="field">
    <%= f.label :presentage %><br>
    <%= f.number_field :presentage %>
  </div>
  <div class="field">
    <%= f.label :institute_name %><br>
    <%= f.text_field :institute_name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div> -->


<h2 style="color:OrangeRed"><center>Certification Details</center></h2>
<hr>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Certification Name</label>
    <div class="col-sm-6">
        <%= f.text_field :certification_name ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"certification Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">presentage </label>
    <div class="col-sm-6">
       <%= f.number_field :presentage ,:class =>"form-control",  :style =>"border:1px groove #F7730E;" , :placeholder=>"  out of 100"%>
    </div>
  </div>
   <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Institute Name</label>
    <div class="col-sm-6">
         <%= f.text_field :institute_name ,:class =>"form-control",  :style =>"border:1px groove #F7730E;" , :placeholder=>"university  Name"%>
    </div>
  </div>
   <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Start date</label>
    <div class="col-sm-6">
      <%= f.date_select :start_date ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"year_of_passing"%>
    </div>
  </div>
    <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">End date</label>
    <div class="col-sm-6">
      <%= f.date_select :end_date ,:class =>"form-control",  :style =>"border:1px groove #F7730E;" , :placeholder=>"year_of_passing"%>
    </div>
  </div>

 <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      
      <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
      <%= f.submit 'Enter Certification Details', :class => 'btn btn-primary'  %>
    </div>
    <img src="/assets/cer.png" alt="Logo"  align="right" style="left: 18px;
top: -294px;" >
  </div>
    <% end %>
</div>
</div>

app/views/certificationals/edit.html.erb
<h1>Editing certificational</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificational %> |
<%= link_to 'Back', certificationals_path %>

app/views/certificationals/index.html.erb
  
  <div class="container">
 <div class="jumbotron">

         <%= link_to 'New Certificational', new_certificational_path, :class=>"pull-right btn btn-default"%>          
      <h2 style="color:OrangeRed"><center>Listing Certification </center></h2>
   
      <hr>
              <div class="panel panel-default">
                <div class="panel-body">
                  <table class="table table-striped footable">
                    <thead>
    <tr>
      <th>Certification name</th>
      <th>Presentage</th>
      <th>Institute name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificationals.reverse.each do |certificational| %>
      <tr>
        <td><%= certificational.certification_name %></td>
        <td><%= certificational.presentage %></td>
        <td><%= certificational.institute_name %></td>
        <td><%= certificational.start_date %></td>
        <td><%= certificational.end_date %></td>
        <td><%= certificational.user_id %></td>
        <td><%= link_to 'Show', certificational %></td>
        <td><%= link_to 'Edit', edit_certificational_path(certificational) %></td>
        <td><%= link_to 'Destroy', certificational, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
 </tbody>
                  </table>
                </div>
              </div>
            </div>

</div>


 

app/views/certificationals/new.html.erb
<h1></h1>

<%= render 'form' %>

app/views/certificationals/show.html.erb
  
  <div class="container">
 <div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>Certification name:</strong>
  <%= @certificational.certification_name %>
</p>

<p>
  <strong>Presentage:</strong>
  <%= @certificational.presentage %>
</p>

<p>
  <strong>Institute name:</strong>
  <%= @certificational.institute_name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @certificational.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @certificational.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @certificational.user_id %>
</p>

<%= link_to 'Edit', edit_certificational_path(@certificational) %> |
<%= link_to 'Back', certificationals_path %>

</div>
</div>