config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :experiences

  resources :profiles

  resources :tech_skills

  resources :certificationals

  resources :educations

  resources :addresses

  resources :employees

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  
  root to: "resumes#index"
   
      get 'index' => "resumes#index"
      get 'about_us' => "resumes#about_us"
      get 'contact_us' => "resumes#contact_us"
      get 'resume_edit' => "resumes#resume_edit"
      get '/export_to_pdf' => "resumes#export_to_pdf"
      get '/resume' => "resumes#resume"
      get '/resume1' => "resumes#resume1"
      get '/resume2' => "resumes#resume2"
      get '/demo_resume' => "resumes#demo_resume"
 
 
    
    
    get "/404", :to => 'errors#file_not_found', via: :all
    get "/422", :to => 'errors#unprocessable', via: :all
    get "/500", :to => 'errors#internal_server_error', via: :all

   

end

app/models/education.rb
# == Schema Information
#
# Table name: educations
#
#  id              :integer          not null, primary key
#  course          :string(255)
#  institute       :string(255)
#  university      :string(255)
#  year_of_passing :date
#  presentage      :integer
#  created_at      :datetime
#  updated_at      :datetime
#  employee_id     :integer
#  user_id         :integer
#

class Education < ActiveRecord::Base
	belongs_to :employee
	belongs_to :users
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
    before_action :authenticate_user!

  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @education = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
     @education_type = ["SSC","HSC","GRADUATION","POST-GRADUATION"]
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    params[:education][:user_id] = current_user.id
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to "/educations", notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:course, :institute, :university, :presentage, :year_of_passing, :user_id)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<div class="container">
 <div class="jumbotron">
 

        
<%= form_for @education ,:html=>{:class=>"form-horizontal" ,:role=>"form"} do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h2 style="color:OrangeRed"><center>Education Details</center></h2><hr>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">course Name</label>
    <div class="col-sm-6">
    <%= f.select :course, options_for_select(@education_type),{:prompt=> "Select Course education_type"},{:class =>"form-control"}%>
      <%#= f.text_field :course ,:class =>"form-control",   :placeholder=>"course name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">institute  Name</label>
    <div class="col-sm-6">
      <%= f.text_field :institute ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,:placeholder=>"institute  Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">university Name</label>
    <div class="col-sm-6">
      <%= f.text_field :university ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"university  Name"%>
    </div>
  </div>
   <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">presentage</label>
    <div class="col-sm-6">
      <%= f.number_field :presentage ,:class =>"form-control", :style =>"border:1px groove #F7730E;" ,  :placeholder=>"out of 100% "%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">year_of_passing</label>
    <div class="col-sm-6">
      <%= f.date_select :year_of_passing ,:class =>"form-control",   :style =>"border:1px groove #F7730E;" ,:placeholder=>"year_of_passing"%>
    </div>
  </div>
  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      
      <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
      <%= f.submit 'Enter Address Details', :class => 'btn btn-primary'  %>
    </div>
       <div id="image">
  <img src="../assets/ed.png" alt="Logo"  align="left" style=" left: 10px;
top: -290px;">
</div>
  </div>
    <% end %>


  </div>
  </div>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
  
  <div class="container">
 <div class="jumbotron">

             <%= link_to 'Add Education', new_education_path, :class =>"btn btn-primary pull-right" %>
     <h2 style="color:OrangeRed"><center>Listing education </center></h2>       
               <hr>
              <div class="panel panel-default">
                <div class="panel-body">
                  <table class="table table-striped footable">
                    <thead>
    <tr>
      <th>Course</th>
      <th>Institute</th>
      <th>University/board</th>
        <th>presentage</th>
      <th>Year of passing</th>
      <th colspan="3">Action </th>
    </tr>
  </thead>

  <tbody>
    <% @education.each do |education| %>
      <tr>
        <td><%= education.course %></td>
        <td><%= education.institute %></td>
        <td><%= education.university %></td>
        <td><%= education.presentage %></td>
        <td><%= education.year_of_passing %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
         
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

</div>

app/views/educations/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
  
  <div class="container">
 <div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @education.course %>
</p>

<p>
  <strong>Institute:</strong>
  <%= @education.institute %>
</p>

<p>
  <strong>University/board:</strong>
  <%= @education.university%>
</p>
<p>
  <strong>presentage:</strong>
  <%= @education.presentage%>
</p>
<p>
  <strong>Year of passing:</strong>
  <%= @education.year_of_passing %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>
</div>
</div>